##############################################################
#  auto-start.ps1  -  One-click dev environment launcher
#  Auto-detects current WiFi/LAN IP and updates mobile/.env
#  Then starts: Python FastAPI (port 8000) + NestJS (port 3000)
##############################################################

$ErrorActionPreference = 'Stop'
$Root = $PSScriptRoot

Write-Host ""
Write-Host "=================================================" -ForegroundColor Cyan
Write-Host "   Fish Price Predictor - Auto Start" -ForegroundColor Cyan
Write-Host "=================================================" -ForegroundColor Cyan
Write-Host ""

# ── Step 1: Auto-detect current LAN/WiFi IP ─────────────────
Write-Host "[1/4] Detecting current network IP..." -ForegroundColor Yellow

$ip = $null

# Method 1: ipconfig (most reliable on all Windows versions)
$ipconfigOut = & ipconfig
$ipMatches = $ipconfigOut | Select-String 'IPv4[^:]*:\s+(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
$candidates = $ipMatches | ForEach-Object { $_.Matches[0].Groups[1].Value } |
              Where-Object { $_ -notmatch '^(127\.|169\.254\.)' }

# Method 2: Get-NetIPAddress fallback (skips virtual/loopback adapters)
if (-not $candidates) {
    try {
        $candidates = Get-NetIPAddress -AddressFamily IPv4 |
            Where-Object {
                $_.PrefixOrigin -in @('Dhcp','Manual') -and
                $_.IPAddress -notmatch '^(127\.|169\.254\.)' -and
                $_.InterfaceAlias -notmatch 'Loopback|VMware|VirtualBox|Hyper-V|WSL|vEthernet|Bluetooth'
            } | Select-Object -ExpandProperty IPAddress
    } catch { }
}

$ip = if ($candidates) { @($candidates)[0] } else { $null }

if (-not $ip) {
    Write-Host "  WARNING: Could not detect LAN IP. Using localhost." -ForegroundColor Red
    $ip = "localhost"
}

Write-Host "  Detected IP: $ip" -ForegroundColor Green

# ── Step 2: Update mobile/.env ──────────────────────────────
Write-Host ""
Write-Host "[2/4] Updating mobile/.env..." -ForegroundColor Yellow

$envPath = Join-Path $Root "mobile\.env"

$newEnvContent = @"
# Auto-generated by auto-start.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# DO NOT edit the IP lines manually - run auto-start.ps1 instead

EXPO_PUBLIC_API_KEY=http://${ip}:3000
EXPO_PUBLIC_PREDICTION_API_URL=http://${ip}:8000
EXPO_PUBLIC_NODE_STORAGE_URL=http://${ip}:3000/uploads
"@

Set-Content -Path $envPath -Value $newEnvContent -Encoding UTF8
Write-Host "  Written: $envPath" -ForegroundColor Green
Write-Host "  EXPO_PUBLIC_API_KEY          = http://$ip:3000" -ForegroundColor Cyan
Write-Host "  EXPO_PUBLIC_PREDICTION_API_URL = http://$ip:8000" -ForegroundColor Cyan

# ── Step 3: Start Python FastAPI server ─────────────────────
Write-Host ""
Write-Host "[3/4] Starting Python FastAPI (port 8000)..." -ForegroundColor Yellow

$venvPython = Join-Path $Root ".venv\Scripts\python.exe"
$modelDir   = Join-Path $Root "model"

if (-not (Test-Path $venvPython)) {
    Write-Host "  WARNING: .venv not found at $venvPython" -ForegroundColor Red
    Write-Host "  Run: python -m venv .venv && .venv\Scripts\pip install -r model\requirements.txt" -ForegroundColor Red
} else {
    Start-Process -FilePath "powershell.exe" -ArgumentList @(
        "-NoExit",
        "-Command",
        "Set-Location '$modelDir'; & '$venvPython' -m uvicorn api_server:app --host 0.0.0.0 --port 8000 --reload"
    ) -WindowStyle Normal
    Write-Host "  FastAPI started in new window -> http://$ip:8000" -ForegroundColor Green
}

# ── Step 4: Start NestJS backend ────────────────────────────
Write-Host ""
Write-Host "[4/4] Starting NestJS backend (port 3000)..." -ForegroundColor Yellow

$backendDir = Join-Path $Root "Backend"
$npmCmd     = "npm"

Start-Process -FilePath "powershell.exe" -ArgumentList @(
    "-NoExit",
    "-Command",
    "Set-Location '$backendDir'; $npmCmd run start:dev"
) -WindowStyle Normal

Write-Host "  NestJS started in new window -> http://$ip:3000" -ForegroundColor Green

# ── Done ────────────────────────────────────────────────────
Write-Host ""
Write-Host "=================================================" -ForegroundColor Cyan
Write-Host "  All services launching!" -ForegroundColor Green
Write-Host ""
Write-Host "  FastAPI  -> http://$ip:8000/docs" -ForegroundColor White
Write-Host "  NestJS   -> http://$ip:3000" -ForegroundColor White
Write-Host ""
Write-Host "  Now start Expo:" -ForegroundColor White
Write-Host "  cd mobile && npx expo start" -ForegroundColor Yellow
Write-Host "=================================================" -ForegroundColor Cyan
Write-Host ""
