/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onBoard3` | `/onBoard3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/selectSignIn` | `/selectSignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/Market` | `/Market`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/Notifications` | `/Notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/Quality` | `/Quality`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onBoard3` | `/onBoard3`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/selectSignIn` | `/selectSignIn`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/Market` | `/Market`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/Notifications` | `/Notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/Quality` | `/Quality`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onBoard3${`?${string}` | `#${string}` | ''}` | `/onBoard3${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/selectSignIn${`?${string}` | `#${string}` | ''}` | `/selectSignIn${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/Market${`?${string}` | `#${string}` | ''}` | `/Market${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/Notifications${`?${string}` | `#${string}` | ''}` | `/Notifications${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/Quality${`?${string}` | `#${string}` | ''}` | `/Quality${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onBoard3` | `/onBoard3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/selectSignIn` | `/selectSignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/Market` | `/Market`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/Notifications` | `/Notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/Quality` | `/Quality`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
