# Mobile App Auto-Setup Script
# Automatically detects backend IP address and creates .env file

Write-Host "=====================================" -ForegroundColor Cyan
Write-Host "Mobile App - Backend Discovery" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "Scanning for backend servers..." -ForegroundColor Yellow
Write-Host ""

$PYTHON_PORT = 8000
$NESTJS_PORT = 5000

# Get list of potential IPs on the local network
$localIPs = Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.IPAddress -notmatch "^127\." -and $_.IPAddress -ne "0.0.0.0" } | Where-Object { $_.InterfaceAlias -like "*Wi-Fi*" -or $_.InterfaceAlias -like "*Ethernet*" }

if ($localIPs.Count -eq 0) {
    Write-Host "ERROR: No network interface found!" -ForegroundColor Red
    exit 1
}

$pcIP = @($localIPs)[0].IPAddress
Write-Host "Detected PC IP: $pcIP" -ForegroundColor Green
Write-Host ""

# Try to connect to backend on detected IP
Write-Host "Testing backend connectivity..." -ForegroundColor Yellow

$testUrl = "http://$pcIP`:$PYTHON_PORT/fish"
$backendFound = $false

try {
    $response = Invoke-WebRequest -Uri $testUrl -TimeoutSec 2 -ErrorAction Stop
    if ($response.StatusCode -eq 200) {
        $backendFound = $true
        Write-Host "[OK] Python API found at http://$pcIP`:$PYTHON_PORT" -ForegroundColor Green
    }
}
catch {
    Write-Host "[WAIT] Backend may still be starting..." -ForegroundColor Yellow
}

Write-Host ""

# Create .env file regardless (backend might be starting)
$envContent = "# Auto-generated by setup-api.ps1`nEXPO_PUBLIC_API_URL=http://$pcIP`:$PYTHON_PORT`nEXPO_PUBLIC_AUTH_URL=http://$pcIP`:$NESTJS_PORT"

Set-Content -Path ".env" -Value $envContent
Write-Host "[OK] Created .env file" -ForegroundColor Green
Write-Host ""
Write-Host "Configuration:" -ForegroundColor Cyan
Write-Host "  Prediction API: http://$pcIP`:$PYTHON_PORT" -ForegroundColor Green
Write-Host "  Auth API:       http://$pcIP`:$NESTJS_PORT" -ForegroundColor Green
Write-Host ""
Write-Host "[OK] Ready to start! Run:" -ForegroundColor Green
Write-Host "  npx expo start" -ForegroundColor Yellow
